import type { Status } from "../types";

// Data files are plain JS (generated by scripts). Re-export with explicit
// types so TS can index them with dynamic strings.

import { categories as rawCategories, categoryOrder as rawOrder } from "./categories.js";
import { statuses as rawStatuses } from "./statuses.js";
import { translations as rawTranslations } from "./translations.js";

export interface Category {
  en: string;
  bn: string;
  emoji: string;
}

export const categories = rawCategories as unknown as Record<string, Category>;
export const categoryOrder = rawOrder as string[];
export const statuses = rawStatuses as unknown as Status[];
export const translations = rawTranslations as unknown as Record<
  string,
  Record<string, string>
>;
