// All supported languages (70 machine-translated + English + Bangla).
// flag: representative country code for flagcdn.com images.

export const LANGUAGES = [
  { code: "en", name: "English", native: "English", flag: "us" },
  { code: "bn", name: "Bengali", native: "বাংলা", flag: "bd" },
  { code: "hi", name: "Hindi", native: "हिन्दी", flag: "in" },
  { code: "ur", name: "Urdu", native: "اردو", flag: "pk" },
  { code: "fa", name: "Persian", native: "فارسی", flag: "ir" },
  { code: "ar", name: "Arabic", native: "العربية", flag: "sa" },
  { code: "he", name: "Hebrew", native: "עברית", flag: "il" },
  { code: "tr", name: "Turkish", native: "Türkçe", flag: "tr" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycanca", flag: "az" },
  { code: "ka", name: "Georgian", native: "ქართული", flag: "ge" },
  { code: "hy", name: "Armenian", native: "Հայերեն", flag: "am" },
  { code: "ru", name: "Russian", native: "Русский", flag: "ru" },
  { code: "be", name: "Belarusian", native: "Беларуская", flag: "by" },
  { code: "uk", name: "Ukrainian", native: "Українська", flag: "ua" },
  { code: "ro", name: "Romanian", native: "Română", flag: "ro" },
  { code: "bg", name: "Bulgarian", native: "Български", flag: "bg" },
  { code: "sr", name: "Serbian", native: "Српски", flag: "rs" },
  { code: "bs", name: "Bosnian", native: "Bosanski", flag: "ba" },
  { code: "hr", name: "Croatian", native: "Hrvatski", flag: "hr" },
  { code: "sl", name: "Slovenian", native: "Slovenščina", flag: "si" },
  { code: "mk", name: "Macedonian", native: "Македонски", flag: "mk" },
  { code: "sq", name: "Albanian", native: "Shqip", flag: "al" },
  { code: "el", name: "Greek", native: "Ελληνικά", flag: "gr" },
  { code: "it", name: "Italian", native: "Italiano", flag: "it" },
  { code: "fr", name: "French", native: "Français", flag: "fr" },
  { code: "es", name: "Spanish", native: "Español", flag: "es" },
  { code: "pt", name: "Portuguese", native: "Português", flag: "br" },
  { code: "de", name: "German", native: "Deutsch", flag: "de" },
  { code: "nl", name: "Dutch", native: "Nederlands", flag: "nl" },
  { code: "da", name: "Danish", native: "Dansk", flag: "dk" },
  { code: "no", name: "Norwegian", native: "Norsk", flag: "no" },
  { code: "sv", name: "Swedish", native: "Svenska", flag: "se" },
  { code: "fi", name: "Finnish", native: "Suomi", flag: "fi" },
  { code: "is", name: "Icelandic", native: "Íslenska", flag: "is" },
  { code: "et", name: "Estonian", native: "Eesti", flag: "ee" },
  { code: "lv", name: "Latvian", native: "Latviešu", flag: "lv" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių", flag: "lt" },
  { code: "pl", name: "Polish", native: "Polski", flag: "pl" },
  { code: "cs", name: "Czech", native: "Čeština", flag: "cz" },
  { code: "sk", name: "Slovak", native: "Slovenčina", flag: "sk" },
  { code: "hu", name: "Hungarian", native: "Magyar", flag: "hu" },
  { code: "ca", name: "Catalan", native: "Català", flag: "ad" },
  { code: "mt", name: "Maltese", native: "Malti", flag: "mt" },
  { code: "ga", name: "Irish", native: "Gaeilge", flag: "ie" },
  { code: "la", name: "Latin", native: "Latina", flag: "va" },
  { code: "sw", name: "Swahili", native: "Kiswahili", flag: "ke" },
  { code: "ha", name: "Hausa", native: "Hausa", flag: "ne" },
  { code: "am", name: "Amharic", native: "አማርኛ", flag: "et" },
  { code: "so", name: "Somali", native: "Soomaali", flag: "so" },
  { code: "rw", name: "Kinyarwanda", native: "Kinyarwanda", flag: "rw" },
  { code: "st", name: "Sesotho", native: "Sesotho", flag: "ls" },
  { code: "ht", name: "Haitian Creole", native: "Kreyòl Ayisyen", flag: "ht" },
  { code: "si", name: "Sinhala", native: "සිංහල", flag: "lk" },
  { code: "ne", name: "Nepali", native: "नेपाली", flag: "np" },
  { code: "km", name: "Khmer", native: "ខ្មែរ", flag: "kh" },
  { code: "lo", name: "Lao", native: "ລາວ", flag: "la" },
  { code: "my", name: "Burmese", native: "မြန်မာ", flag: "mm" },
  { code: "th", name: "Thai", native: "ไทย", flag: "th" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", flag: "vn" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", flag: "id" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu", flag: "my" },
  { code: "tl", name: "Tagalog", native: "Tagalog", flag: "ph" },
  { code: "zh", name: "Chinese", native: "中文", flag: "cn" },
  { code: "ja", name: "Japanese", native: "日本語", flag: "jp" },
  { code: "ko", name: "Korean", native: "한국어", flag: "kr" },
  { code: "mn", name: "Mongolian", native: "Монгол", flag: "mn" },
  { code: "kk", name: "Kazakh", native: "Қазақша", flag: "kz" },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча", flag: "kg" },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ", flag: "tj" },
  { code: "tk", name: "Turkmen", native: "Türkmençe", flag: "tm" },
  { code: "uz", name: "Uzbek", native: "Oʻzbekcha", flag: "uz" },
  { code: "sm", name: "Samoan", native: "Gagana Sāmoa", flag: "ws" },
];

export const SUPPORTED_LANG_CODES = new Set(LANGUAGES.map((l) => l.code));
